#!/bin/bash

set -e

function die {
    echo "error: ${1}"
    exit 1
}

[ -z "${1}" ] && die "must specify on|off"

if [ "${1}" = "on" ]; then
    enable=true
elif [ "${1}" = "off" ]; then
    enable=false
else
    die "argument must be either 'on' or 'off'"
fi

high_dpi_env_path=~/dotfiles/bash/bash.local/high-dpi
if ${enable}; then
    echo "Enabling High-DPI settings ..."

    # set window scaling factor x2 (> Appearance > Settings)
    xfconf-query -c xsettings -p /Gdk/WindowScalingFactor -s 2
    # scale mouse cursor: 24 -> 48 pixels (> Mouse > Theme)
    xfconf-query -c xsettings -p /Gtk/CursorThemeSize -s 48
    # scale window titles
    xfconf-query -c xfwm4 -p /general/title_font -s "Sans Bold 16"

    # scale up fonts with custom DPI: 96 -> 192 (> Appearance > Fonts)
    xfconf-query -c xsettings -p /Xft/DPI -s 192

    # use a high-dpi friendly window manager theme
    xfconf-query -c xfwm4 -p /general/theme -s Default-hdpi

    echo "Adding GDK_DPI_SCALE factor in ${high_dpi_env_path} ..."
    cat > ${high_dpi_env_path} <<EOF
#
# DO NOT EDIT (generated by ${0})
#
export GDK_DPI_SCALE=0.5
EOF

    xfconf-query -c xsettings -p /Gtk/FontName -s "Noto Sans 10"
    xfconf-query -c xsettings -p /Gtk/MonospaceFontName -s "DejaVu Sans Mono 9"
else
    echo "Disabling High-DPI settings ..."
    # set window scaling factor x1 (> Appearance > Settings)
    xfconf-query -c xsettings -p /Gdk/WindowScalingFactor -s 1
    # default mouse cursor: 24 pixels (> Mouse > Theme)
    xfconf-query -c xsettings -p /Gtk/CursorThemeSize -s 24
    # scale window titles
    xfconf-query -c xfwm4 -p /general/title_font -s "Sans Bold 12"

    # normal fonts DPI: 96 (> Appearance > Fonts)
    xfconf-query -c xsettings -p /Xft/DPI -s 96

    # use a default window manager theme
    xfconf-query -c xfwm4 -p /general/theme -s Greybird

    echo "Removing ${high_dpi_env_path} ..."
    rm -f ${high_dpi_env_path}

    xfconf-query -c xsettings -p /Gtk/FontName -s "Noto Sans 12"
    xfconf-query -c xsettings -p /Gtk/MonospaceFontName -s "DejaVu Sans Mono 12"
fi
