#!/bin/bash

set -e

function die {
    echo "error: ${1}"
    exit 1
}

[ -z "${1}" ] && die "must specify on|off"

if [ "${1}" = "on" ]; then
    enable=true
elif [ "${1}" = "off" ]; then
    enable=false
else
    die "argument must be either 'on' or 'off'"
fi

high_dpi_env_path=~/dotfiles/bash/bash.local/high-dpi
if ${enable}; then
    echo "Enabling High-DPI settings ..."

    # TODO: no longer appears needed?
    # set window scaling factor x2 (> Appearance > Settings)
    # xfconf-query -c xsettings -p /Gdk/WindowScalingFactor -s 2

    # Scale mouse cursor: 24 -> 48 pixels (> Mouse > Theme).
    xfconf-query -c xsettings -p /Gtk/CursorThemeSize -s 48
    # Scale window titles.
    xfconf-query -c xfwm4 -p /general/title_font -s "Sans Bold 8"
    # Scale system fonts.
    xfconf-query -c xsettings -p /Gtk/FontName -s "Noto Sans 9"
    xfconf-query -c xsettings -p /Gtk/MonospaceFontName -s "DejaVu Sans Mono 9"

    # Scale up fonts with custom DPI: 96 -> 192 (> Appearance > Fonts). Needed
    # e.g. to get larger font-size in web browser and chat clients
    # (slack/mattermost).
    xfconf-query -c xsettings -p /Xft/DPI -s 192

    # Set the height in pixels of the top panel row.
    xfconf-query -c xfce4-panel -p /panels/panel-1/size -s 40


    # TODO: no longer appears necessary?
#     echo "Adding GDK_DPI_SCALE factor in ${high_dpi_env_path} ..."
#     cat > ${high_dpi_env_path} <<EOF
# #
# # DO NOT EDIT (generated by ${0})
# #
# export GDK_DPI_SCALE=0.5
# EOF


else
    echo "Disabling High-DPI settings ..."
    # Set normal window scaling factor x1 (> Appearance > Settings).
    xfconf-query -c xsettings -p /Gdk/WindowScalingFactor -s 1

    # Default size mouse cursor: 24 pixels (> Mouse > Theme).
    xfconf-query -c xsettings -p /Gtk/CursorThemeSize -s 24
    # Scale window titles.
    xfconf-query -c xfwm4 -p /general/title_font -s "Sans Bold 12"
    # Scale system fonts.
    xfconf-query -c xsettings -p /Gtk/FontName -s "Noto Sans 12"
    xfconf-query -c xsettings -p /Gtk/MonospaceFontName -s "DejaVu Sans Mono 12"

    # Default font DPI: 96 (> Appearance > Fonts).
    xfconf-query -c xsettings -p /Xft/DPI -s 96

    # Set the height in pixels of the top panel row.
    xfconf-query -c xfce4-panel -p /panels/panel-1/size -s 24

    # TODO no longer necessary?
    # echo "Removing ${high_dpi_env_path} ..."
    # rm -f ${high_dpi_env_path}

    # xfconf-query -c xsettings -p /Gtk/FontName -s "Noto Sans 12"
    # xfconf-query -c xsettings -p /Gtk/MonospaceFontName -s "DejaVu Sans Mono 12"
fi

xfce4-panel --restart
