" ### START: Vundle plugin manager ###
set nocompatible              " be iMproved, required
filetype off                  " required
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

" NOTE: Keep plugin declarations between vundle#begin/end
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Solarized theme
Plugin 'altercation/vim-colors-solarized'

" Status line at bottom of screen
Plugin 'bling/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

" file navigation panel
Plugin 'scrooloose/nerdtree'

call vundle#end()            " required
filetype plugin indent on    " required
" ### END: Vundle plugin manager ###


" prefer utf-8 file encoding
set encoding=utf-8      " The encoding displayed
set fileencoding=utf-8  " The encoding written to 

" copy/paste to/from system clipboard
"set clipboard=unnamedplus

" enable syntax highlighting
syntax enable

" enable line numbers
set number

"navigating betwen split windows
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Enable Solarized theme only in graphical mode
if has('gui_running')
  set background=dark
  colorscheme solarized
endif

" always display status line (for airline to be displayed at all times)
set laststatus=2
set ttimeoutlen=50

